version: '3.8'

services:
  homeapp-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: homeapp-frontend
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/node/app:delegated
      - /node/app/node_modules
    networks:
      - mynet
    ports:
      - 4173:4173
      - 5173:5173

  homeapp-backend:
    depends_on: 
      - postgres
    build:
      context: ./backend/
    container_name: homeapp-backend
    hostname: homeapp-backend
    networks:
      - mynet
    ports:
      - 8080:8080
    # environment:

    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - mynet
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - ./backend/.env
    volumes:
       - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - mynet
    restart: unless-stopped

volumes:
  mongo:
  postgres:

networks:
  mynet:
    driver: bridge