version: '3.8'

services:
  docker-gs-ping-roach:
    depends_on: 
      - postgres
    build:
      context: ./backend/
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:

    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme11}
      PGDATA: /data/postgres
    volumes:
      #  - postgres:/data/postgres
       - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynet
    restart: unless-stopped

volumes:
  postgres:

networks:
  mynet:
    driver: bridge